### PR TITLE
Parse more data

### PR DESCRIPTION
**Pull request by mcronce**
This updates the lib to parse HP/MP, attributes, and each job's current/max XP.  It'll tick a bunch of the boxes in #3.

### CODE REVIEW

**Comment by mcronce** [comment]
Also just noticed I accidentally included `Profile::all_class_info()`; I can take this back out and put it in a separate PR, but do need it for my use case

**Comment by Roughsketch** [comment]
Thank you very much for taking an interest in this crate and making a PR for it!

In order to test this PR I've made a new test case. To get it into this PR I've made my own PR onto this branch so you can work with it. It uses a dead account to pull information from, so unfortunately it's not able to test out anything new but it can provide a base for seeing how well it scrapes data.

The only input I have is that for any new public function I would like there to be doc comments so that the auto-generated docs explain the usage of the method to new people. The ones I see missing are for the following:

- Attribute struct definition
- Attributes `get`
- ClassInfo struct definition
- Classes `get` (This one looks like my mistake)
- Profile `class_info` and `all_class_info`

Besides that I would like for new information to be added to tests just to make sure that it grabs information correctly.

**Comment by mcronce** [comment]
Just as a heads up, I haven't forgotten about this (nor the other stuff I want to add ;)), I just haven't had time to address these yet

**Comment by mcronce** [comment]
Alrighty, I think this is good to go @Roughsketch - let me know if it looks like I've missed anything or you want anything changed.

Thanks!

**Review by Roughsketch — APPROVED** [review]
Looks good to me. Going to merge this and then update the dependencies to their current versions before releasing 0.4.0.

Thanks for the PR!

**Comment by mcronce** [comment]
No problem :) I have more coming once I have time that will check off more of the boxes in #3

**Pull request merged**
